import os, json, urllib.request, time

# Robust script to copy Feishu blocks from a Temp Document (e.g. from Markdown Import)
# into a Target Document, correctly handling Feishu's strict Block API rules:
# 1. Strips all `block_id`s.
# 2. Extracts only `row_size`, `column_size`, `column_width` for tables.
# 3. Splits tables > 9 rows into consecutive smaller tables to prevent HTTP 400 (1770001).
# 4. Batches block insertions into chunks of 40 to avoid timeouts.
# 5. Sequentially traverses and maps children blocks for table cells.


def do_req(token, url, method="GET", payload=None):
    req = urllib.request.Request(
        url, headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"}, method=method
    )
    if payload:
        req.data = json.dumps(payload).encode()
    for _ in range(3):
        try:
            return json.loads(urllib.request.urlopen(req).read())
        except urllib.error.HTTPError as e:
            if e.code == 429:
                time.sleep(2)
                continue
            print(e.read().decode())
            raise e


def merge_docs(token, source_doc_token, target_doc_token):
    # 1. Read source blocks
    res = do_req(
        token, f"https://open.feishu.cn/open-apis/docx/v1/documents/{source_doc_token}/blocks/{source_doc_token}"
    )
    source_root = res["data"]["block"]

    res_blocks = do_req(
        token, f"https://open.feishu.cn/open-apis/docx/v1/documents/{source_doc_token}/blocks?page_size=500"
    )
    blocks = res_blocks["data"]["items"]
    block_map = {b["block_id"]: b for b in blocks}

    # 2. Tree builder
    def build_tree(block_id):
        b = block_map[block_id]
        node = {"block_type": b["block_type"]}
        keys_to_copy = [
            "text",
            "heading1",
            "heading2",
            "heading3",
            "heading4",
            "heading5",
            "heading6",
            "heading7",
            "heading8",
            "heading9",
            "bullet",
            "ordered",
            "code",
            "quote",
            "todo",
            "callout",
            "divider",
            "grid",
            "equation",
        ]
        for k in keys_to_copy:
            if k in b:
                node[k] = b[k]
                if isinstance(node[k], dict) and "style" in node[k]:
                    del node[k]["style"]
        if "text" in node or "bullet" in node or "ordered" in node:
            for k in ["text", "bullet", "ordered"]:
                if k in node:
                    for el in node[k].get("elements", []):
                        if "text_run" in el and "text_element_style" in el["text_run"]:
                            el["text_run"]["text_element_style"] = {
                                k2: v2 for k2, v2 in el["text_run"]["text_element_style"].items() if v2
                            }
                            if not el["text_run"]["text_element_style"]:
                                del el["text_run"]["text_element_style"]

        if b["block_type"] == 31:  # Table
            node["table"] = {
                "property": {
                    "row_size": b["table"]["property"]["row_size"],
                    "column_size": b["table"]["property"]["column_size"],
                }
            }
            if "column_width" in b["table"]["property"]:
                node["table"]["property"]["column_width"] = b["table"]["property"]["column_width"]
            return node

        if b.get("children"):
            node["children"] = [build_tree(cid) for cid in b["children"] if cid in block_map]
        return node

    # Extract top-level children
    temp_children = source_root.get("children", [])
    if temp_children and block_map[temp_children[0]]["block_type"] == 3:
        temp_children = temp_children[1:]  # Skip H1 title block if generated by markdown import

    # 3. Batch and Insert
    chunk_size = 40
    chunks = [temp_children[i : i + chunk_size] for i in range(0, len(temp_children), chunk_size)]

    for chunk_ids in chunks:
        # We need to maintain order. We can't batch non-tables at the end of the chunk
        # if there are tables mixed in. So we will batch non-tables until we hit a table,
        # then POST the batch, then POST the table, then continue.
        payload_chunk = []

        def flush_payload():
            if payload_chunk:
                do_req(
                    token,
                    f"https://open.feishu.cn/open-apis/docx/v1/documents/{target_doc_token}/blocks/{target_doc_token}/children",
                    method="POST",
                    payload={"children": payload_chunk, "index": -1},
                )
                payload_chunk.clear()

        for cid in chunk_ids:
            b = block_map[cid]
            if b["block_type"] == 31:
                flush_payload()
                # Handle Table splitting (>9 rows limit)
                col_size = b["table"]["property"]["column_size"]
                col_width = b["table"]["property"].get("column_width")
                orig_cells = b["table"]["cells"]

                cells_processed = 0
                while cells_processed < len(orig_cells):
                    rem_rows = (len(orig_cells) - cells_processed) // col_size
                    curr_rows = min(rem_rows, 9)

                    payload_table = {
                        "block_type": 31,
                        "table": {"property": {"row_size": curr_rows, "column_size": col_size}},
                    }
                    if col_width:
                        payload_table["table"]["property"]["column_width"] = col_width

                    res_table = do_req(
                        token,
                        f"https://open.feishu.cn/open-apis/docx/v1/documents/{target_doc_token}/blocks/{target_doc_token}/children",
                        method="POST",
                        payload={"children": [payload_table], "index": -1},
                    )
                    new_cells = res_table["data"]["children"][0]["table"]["cells"]

                    # Map nested cell contents
                    for k, new_cell_id in enumerate(new_cells):
                        orig_cell_idx = cells_processed + k
                        if orig_cell_idx < len(orig_cells):
                            cell_children_ids = block_map[orig_cells[orig_cell_idx]].get("children", [])
                            if cell_children_ids:
                                cell_payload = [build_tree(ccid) for ccid in cell_children_ids]
                                do_req(
                                    token,
                                    f"https://open.feishu.cn/open-apis/docx/v1/documents/{target_doc_token}/blocks/{new_cell_id}/children",
                                    method="POST",
                                    payload={"children": cell_payload, "index": -1},
                                )
                        try:
                            # Delete default empty block in new cell
                            do_req(
                                token,
                                f"https://open.feishu.cn/open-apis/docx/v1/documents/{target_doc_token}/blocks/{new_cell_id}/children/batch_delete",
                                method="DELETE",
                                payload={"start_index": 0, "end_index": 1},
                            )
                        except Exception as ignore:
                            pass

                    cells_processed += curr_rows * col_size
            else:
                payload_chunk.append(build_tree(cid))

        flush_payload()
